version: '3.8'

services:
  database:
    container_name: tww-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql/var/lib/mysql:/var/lib/mysql
      - ./docker/mysql/initdb/test-cinemahd-database.sql:/test-cinemahd-database.sql
      - ./docker/mysql/initdb/test-cinemahd-datas.sql:/test-cinemahd-datas.sql
    networks:
      - tww-symfony

  php:
    container_name: tww-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - database
    networks:
      - tww-symfony

  nginx:
    container_name: tww-nginx
    image: nginx:1.17
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - tww-symfony

networks:
  tww-symfony:
    driver: bridge

