security:
    enable_authenticator_manager: true
    providers:
        api_key:
            entity:
                class: App\Entity\User
                property: key
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
            pattern: ^/api
            provider: api_key
            stateless: true

    access_control:
        - { path: ^/api/(movies|movies_has_people|movies_has_type|peoples|type)/, allow_if: "is_fully_authenticated()", methods: [POST, PUT, DELETE] }
        - { path: ^/api/(movies|movies_has_people|movies_has_type|peoples|type)/, allow_if: "is_anonymous() or is_fully_authenticated()", methods: [GET] }
